In [84]:
import numpy as np
import pandas as pd

In [85]:
df = pd.read_csv('./feruse.csv')

In [86]:
print(df.head)

<bound method NDFrame.head of        emotion                                             pixels        Usage
0            0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...     Training
1            0  151 150 147 155 148 133 111 140 170 174 182 15...     Training
2            2  231 212 156 164 174 138 161 173 182 200 106 38...     Training
3            4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...     Training
4            6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...     Training
...        ...                                                ...          ...
35882        6  50 36 17 22 23 29 33 39 34 37 37 37 39 43 48 5...  PrivateTest
35883        3  178 174 172 173 181 188 191 194 196 199 200 20...  PrivateTest
35884        0  17 17 16 23 28 22 19 17 25 26 20 24 31 19 27 9...  PrivateTest
35885        3  30 28 28 29 31 30 42 68 79 81 77 67 67 71 63 6...  PrivateTest
35886        2  19 13 14 12 13 16 21 33 50 57 71 84 97 108 122...  PrivateTest

[35887 rows x 3 colum

In [87]:
df['emotion'].head

<bound method NDFrame.head of 0        0
1        0
2        2
3        4
4        6
        ..
35882    6
35883    3
35884    0
35885    3
35886    2
Name: emotion, Length: 35887, dtype: int64>

In [88]:
X_test, X_train, y_test, y_train = [], [] ,[], []

In [89]:
for index, row in df.iterrows():
    val = row['pixels'].split(" ")    
    if 'Training' in row['Usage']:
        X_train.append(np.array(val, dtype = np.float32))
        y_train.append(row['emotion'])
    elif 'PublicTest' in row['Usage']:
        X_test.append(np.array(val, dtype = np.float32))
        y_test.append(row['emotion'])

In [90]:
X_test

[array([254., 254., 254., ...,  42., 129., 180.], dtype=float32),
 array([156., 184., 198., ..., 172., 167., 161.], dtype=float32),
 array([ 69., 118.,  61., ...,  88.,  87.,  90.], dtype=float32),
 array([205., 203., 236., ...,  43.,  82.,  86.], dtype=float32),
 array([87., 79., 74., ..., 41., 34., 32.], dtype=float32),
 array([235., 233., 223., ...,  33.,  17.,  19.], dtype=float32),
 array([ 71.,  70., 104., ..., 127., 105., 108.], dtype=float32),
 array([176., 177., 170., ..., 130., 144., 141.], dtype=float32),
 array([255., 255., 255., ..., 255., 255., 255.], dtype=float32),
 array([126., 126., 123., ..., 130.,  97.,  78.], dtype=float32),
 array([180., 175., 169., ...,  32.,  32.,  33.], dtype=float32),
 array([ 88.,  46.,  35., ..., 229., 228., 227.], dtype=float32),
 array([121., 112.,  64., ...,  81.,  83.,  85.], dtype=float32),
 array([165., 203., 211., ..., 189., 178., 167.], dtype=float32),
 array([22., 28., 27., ..., 90., 81., 92.], dtype=float32),
 array([132., 154., 16

In [91]:
X_train = np.array(X_train, dtype = 'float32')
y_train = np.array(y_train, dtype = 'float32')
X_test = np.array(X_test, 'float32')
y_test = np.array(y_test, dtype = 'float32')

In [92]:
X_test.shape

(3589, 2304)

In [93]:
X_train -= np.mean(X_train, axis=0)
X_train /= np.std(X_train, axis=0)

X_test -= np.mean(X_test, axis=0)
X_test /= np.std(X_test, axis=0)

# X_train /= 255
# X_test/= 255

In [94]:
X_train = X_train.reshape(X_train.shape[0], 48, 48, 1)

In [95]:
X_train.shape

(28709, 48, 48, 1)

In [96]:
X_test = X_test.reshape(X_test.shape[0], 48, 48, 1)


In [97]:
import tensorflow as tf
from tensorflow.keras import utils

In [98]:
y_train[0:10]

array([0., 0., 2., 4., 6., 2., 4., 3., 3., 2.], dtype=float32)

In [99]:
y_train = utils.to_categorical(y_train, num_classes = 7)
y_test =  utils.to_categorical(y_test, num_classes = 7)

In [100]:
y_train[0:10]

array([[1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]], dtype=float32)

In [101]:
X_train[0:10]

array([[[[-0.6098866 ],
         [-0.4592209 ],
         [-0.40325198],
         ...,
         [-0.7694696 ],
         [-0.90518403],
         [-0.95160526]],

        [[-0.66049284],
         [-0.68162924],
         [-0.694159  ],
         ...,
         [-0.7112763 ],
         [-0.7862608 ],
         [-0.90819967]],

        [[-0.83170736],
         [-0.8952668 ],
         [-0.73603356],
         ...,
         [-0.7924775 ],
         [-0.7261497 ],
         [-0.8613453 ]],

        ...,

        [[-0.33269772],
         [-0.6514918 ],
         [-0.93670547],
         ...,
         [-0.5265123 ],
         [-0.7377333 ],
         [-0.9078971 ]],

        [[-0.5099617 ],
         [-0.43692893],
         [-0.46537215],
         ...,
         [-0.10019822],
         [-0.5580577 ],
         [-0.86989194]],

        [[-0.5095401 ],
         [-0.56317693],
         [-0.3986179 ],
         ...,
         [-0.08629682],
         [-0.0573744 ],
         [-0.41127437]]],


       [[[ 0.37236458],


In [102]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array

datagen = ImageDataGenerator(rotation_range = 40, zoom_range = 0.5, width_shift_range = 0.2, height_shift_range = 0.2, 
                             shear_range = 0.2, horizontal_flip = True, vertical_flip = True, fill_mode = "nearest")

datagen.fit(X_train)

In [113]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D, BatchNormalization,AveragePooling2D

# model = tf.keras.models.Sequential()
# model.add(Conv2D(64, kernel_size=(3, 3), activation='relu', input_shape=(X_train.shape[1:])))
# model.add(Conv2D(64,kernel_size= (3, 3), activation='relu'))
# model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2)))
# # model.add(Dropout(0.2))

# # 2nd convolution layer
# model.add(Conv2D(128, (3, 3), activation='relu'))
# model.add(Conv2D(128, (3, 3), activation='relu'))
# model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2)))
# # model.add(Dropout(0.2))

# # #3rd convolution layer
# model.add(Conv2D(256, (3, 3), activation='relu'))
# model.add(Conv2D(256, (3, 3), activation='relu'))
# model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2)))
# # model.add(Dropout(0.25))

# #4th convolution layer
# model.add(Conv2D(512, (3, 3), activation='relu', padding = "same"))
# model.add(Conv2D(512, (3, 3), activation='relu', padding = "same"))
# model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2)))
# # model.add(Dropout(0.25))

# model.add(Flatten())

# #fully connected neural networks
# # model.add(Dense(1024, activation='relu'))
# # model.add(Dropout(0.45))
# model.add(Dense(512, activation='relu'))
# # model.add(Dropout(0.45))

# model.add(Dense(7, activation='softmax'))

num_features = 64
model = tf.keras.models.Sequential()

model.add(Conv2D(num_features, kernel_size=(3, 3), activation='relu', input_shape=(48, 48, 1), data_format='channels_last', kernel_regularizer=tf.keras.regularizers.l2(0.01)))
model.add(Conv2D(num_features, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
# model.add(Dropout(0.5))

model.add(Conv2D(2*num_features, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(Conv2D(2*num_features, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
# model.add(Dropout(0.5))

model.add(Conv2D(2*2*num_features, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(Conv2D(2*2*num_features, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
# model.add(Dropout(0.5))

model.add(Conv2D(2*2*2*num_features, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(Conv2D(2*2*2*num_features, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
# model.add(Dropout(0.5))

model.add(Flatten())

model.add(Dense(2*2*2*num_features, activation='relu'))
# model.add(Dropout(0.4))
model.add(Dense(2*2*num_features, activation='relu'))
# model.add(Dropout(0.4))
model.add(Dense(2*num_features, activation='relu'))
# model.add(Dropout(0.5))

model.add(Dense(7, activation='softmax'))


# model = Sequential()

# model.add(Conv2D(64, kernel_size=(3, 3), activation='relu', input_shape=(X_train.shape[1:])))
# model.add(Conv2D(64,kernel_size= (3, 3), activation='relu'))
# # model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2), strides=(2, 2)))
# model.add(Dropout(0.5))

# #2nd convolution layer
# model.add(Conv2D(64, (3, 3), activation='relu'))
# model.add(Conv2D(64, (3, 3), activation='relu'))
# # model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2), strides=(2, 2)))
# model.add(Dropout(0.5))

# #3rd convolution layer
# model.add(Conv2D(128, (3, 3), activation='relu'))
# model.add(Conv2D(128, (3, 3), activation='relu'))
# # model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2), strides=(2, 2)))

# model.add(Flatten())

# #fully connected neural networks
# model.add(Dense(1024, activation='relu'))
# model.add(Dropout(0.2))
# model.add(Dense(1024, activation='relu'))
# model.add(Dropout(0.2))

# model.add(Dense(7, activation='softmax'))

In [114]:
model.compile( optimizer = tf.keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-7), loss = tf.keras.losses.categorical_crossentropy, metrics = ['accuracy'])

In [115]:
len(X_train)

28709

In [116]:
model.fit_generator(datagen.flow(X_train, y_train, batch_size =32),steps_per_epoch = len(X_train)/32, epochs = 40, verbose = 1,  validation_data=(X_test, y_test ), shuffle = True)

  ...
    to  
  ['...']
Train for 897.15625 steps, validate on 3589 samples
Epoch 1/40
898/897 [==============================] - 69s 76ms/step - loss: 1.8485 - accuracy: 0.2368 - val_loss: 1.7998 - val_accuracy: 0.2644
Epoch 2/40
898/897 [==============================] - 65s 72ms/step - loss: 1.7935 - accuracy: 0.2554 - val_loss: 1.7859 - val_accuracy: 0.2641
Epoch 3/40
898/897 [==============================] - 65s 72ms/step - loss: 1.7761 - accuracy: 0.2677 - val_loss: 1.7527 - val_accuracy: 0.2862
Epoch 4/40
898/897 [==============================] - 65s 72ms/step - loss: 1.7566 - accuracy: 0.2788 - val_loss: 1.7493 - val_accuracy: 0.2909
Epoch 5/40
898/897 [==============================] - 65s 72ms/step - loss: 1.7397 - accuracy: 0.2898 - val_loss: 1.7562 - val_accuracy: 0.2714
Epoch 6/40
898/897 [==============================] - 65s 72ms/step - loss: 1.7174 - accuracy: 0.3008 - val_loss: 1.6621 - val_accuracy: 0.3288
Epoch 7/40
898/897 [==============================] - 65s 7

In [28]:
model.save(".h5")